// Generated by CoffeeScript 1.6.3
(function() {
  var RESOURCES, makeDefaultResourceManager, root;

  RESOURCES = [['shaders/hyperbolic', 'assets/shaders/hyperbolic.glsl'], ['shaders/elliptic', 'assets/shaders/elliptic.glsl'], ['shaders/euclidean', 'assets/shaders/euclidean.glsl'], ['shaders/postprocess', '../assets/shaders/postprocess.glsl'], ['shaders/nothing', '../assets/shaders/nothing.glsl'], ['space/spaceship', 'assets/textures/spaceship.png']];

  makeDefaultResourceManager = function() {
    var resmgr;
    resmgr = new cofgl.ResourceManager;
    resmgr.addFromList(RESOURCES);
    return resmgr;
  };

  root = self.cofgl != null ? self.cofgl : self.cofgl = {};

  root.makeDefaultResourceManager = makeDefaultResourceManager;

}).call(this);
