// Generated by CoffeeScript 1.6.3
(function() {
  var SpaceShip, root;

  SpaceShip = (function() {
    function SpaceShip() {
      this.texture = cofgl.Texture.fromImage(cofgl.resmgr.resources['space/spaceship'], {
        mipmaps: true,
        filtering: 'LINEAR'
      });
      this.q = new cofgl.Complex(0.0, 0.0);
      this.p = new cofgl.Complex(0.0, 0.0);
      this.dir = 0.0;
    }

    SpaceShip.prototype.update = function(dt) {
      var _ref;
      return _ref = cofgl.poincareStep(this.q, this.p, dt), this.q = _ref[0], this.p = _ref[1], _ref;
    };

    SpaceShip.prototype.rotateLeft = function() {
      return this.dir = this.dir + 0.05;
    };

    SpaceShip.prototype.rotateRight = function() {
      return this.dir = this.dir - 0.05;
    };

    SpaceShip.prototype.thurst = function() {
      var v;
      v = this.dirVec();
      v.x = v.x / 10.0;
      v.y = v.y / 10.0;
      this.p = this.p.plus(v);
      return console.debug("p = " + this.p);
    };

    SpaceShip.prototype.dirVec = function() {
      return new cofgl.Complex(Math.cos(this.dir), Math.sin(this.dir));
    };

    return SpaceShip;

  })();

  root = self.cofgl != null ? self.cofgl : self.cofgl = {};

  root.SpaceShip = SpaceShip;

}).call(this);
